I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 13, in script
    define moe = Character(moe_name, image="moe", dynamic=True)
  File "game/script.rpy", line 13, in <module>
    define moe = Character(moe_name, image="moe", dynamic=True)
NameError: name 'moe_name' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 13, in script
    define moe = Character(moe_name, image="moe", dynamic=True)
  File "C:\Users\arcan\Downloads\renpy-8.2.1-sdk\renpy\ast.py", line 2219, in execute
    self.set()
  File "C:\Users\arcan\Downloads\renpy-8.2.1-sdk\renpy\ast.py", line 2233, in set
    value = renpy.python.py_eval_bytecode(self.code.bytecode)
  File "C:\Users\arcan\Downloads\renpy-8.2.1-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 13, in <module>
    define moe = Character(moe_name, image="moe", dynamic=True)
NameError: name 'moe_name' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.1.24030407
Detective Meowth 1.0
Wed Mar 13 04:13:39 2024
