I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1189, in script
    show moe talk at right, talk_jump
Exception: Image 'moe' does not accept attributes 'talk'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1189, in script
    show moe talk at right, talk_jump
  File "C:\Users\Myltrex\Downloads\renpy-8.2.1-sdk\renpy\ast.py", line 1113, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\Myltrex\Downloads\renpy-8.2.1-sdk\renpy\ast.py", line 1076, in show_imspec
    renpy.config.show(name,
  File "C:\Users\Myltrex\Downloads\renpy-8.2.1-sdk\renpy\exports.py", line 739, in show
    if not base.find_target() and renpy.config.missing_show:
  File "C:\Users\Myltrex\Downloads\renpy-8.2.1-sdk\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "C:\Users\Myltrex\Downloads\renpy-8.2.1-sdk\renpy\display\layout.py", line 162, in _duplicate
    args.extraneous()
  File "C:\Users\Myltrex\Downloads\renpy-8.2.1-sdk\renpy\display\displayable.py", line 109, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'moe' does not accept attributes 'talk'.

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.1.24030407
Detective Meowth 1.0
Tue Mar 19 05:10:33 2024
